COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_SRCDIRS := src
CXXFLAGS += -DESPRESSIO_OBSERVER
CXXFLAGS += -DESPRESSIO_OBSERVER_VERSION_MAJOR=0
CXXFLAGS += -DESPRESSIO_OBSERVER_VERSION_MINOR=0
CXXFLAGS += -DESPRESSIO_OBSERVER_VERSION_PATCH=1
CXXFLAGS += -DESPRESSIO_OBSERVER_VERSION_STRING=\"0.0.1\"