COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src
CXXFLAGS += -DESPRESSIO_OBSERVER
CXXFLAGS += -DESPRESSIO_OBSERVER_VERSION_MAJOR=2
CXXFLAGS += -DESPRESSIO_OBSERVER_VERSION_MINOR=0
CXXFLAGS += -DESPRESSIO_OBSERVER_VERSION_PATCH=0
CXXFLAGS += -DESPRESSIO_OBSERVER_VERSION_STRING=\"2.0.0\"
